#!/usr/bin/env bash
# sync.sh — Linux/Mac equivalent of sync.bat (web files only, no Android/git steps)
# Run this after editing root files to keep www/ in sync for Capacitor Android builds.

set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WWW="$SCRIPT_DIR/www"

echo "============================="
echo " ChronaSense - Sync www/"
echo "============================="

mkdir -p "$WWW"

echo ""
echo "[1/2] Copying files to www/ ..."
cp -f "$SCRIPT_DIR/index.html" "$WWW/index.html"
for f in "$SCRIPT_DIR"/*.js "$SCRIPT_DIR"/*.css; do
  [ -f "$f" ] && cp -f "$f" "$WWW/$(basename "$f")"
done
if [ -d "$SCRIPT_DIR/Sounds" ]; then
  mkdir -p "$WWW/Sounds"
  cp -f "$SCRIPT_DIR/Sounds/"* "$WWW/Sounds/" 2>/dev/null || true
fi

echo ""
echo "[2/2] Adding DO-NOT-EDIT header to www/index.html ..."
if ! grep -q "DO NOT EDIT" "$WWW/index.html"; then
  sed -i '1s/^/<!-- DO NOT EDIT — auto-generated by sync.bat \/ sync.sh. Edit root files instead. -->\n/' "$WWW/index.html"
fi

echo ""
echo "============================="
echo " Done! www/ is up to date."
echo " To build Android: run sync.bat on Windows, then open Android Studio."
echo "============================="
